# Generated by Django 5.1.4 on 2024-12-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='individual_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
