# Generated by Django 5.1.4 on 2024-12-22 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_customer_customuser'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('wagtailadmin', '0005_editingsession_is_editing'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
        ('wagtailusers', '0014_userprofile_contrast'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='Customer',
        ),
    ]
