# Generated by Django 5.1.4 on 2024-12-22 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_customuser_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='discount',
        ),
    ]
